apiVersion: v1
data:
  .dockerconfigjson: [REDACTED]
kind: Secret
metadata:
  creationTimestamp: "2023-10-24T07:11:15Z"
  name: pull-secret
  namespace: openshift-config
  resourceVersion: "1708"
  uid: b890371d-8e17-4741-8668-b8845048f11f
type: kubernetes.io/dockerconfigjson